apiVersion: v1
kind: Secret
metadata:
    name: speedtest-secret
    namespace: speedtest-tracker
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:WSKnEk2vVkWHtZdWi0ufxrY7SeO0CY0N/Nu6Vhg5o47Wmw6+ftHhrOp2IWSbPu5Jmqkd,iv:tVdgkqbbYx3idTEVeMaMcpsKIuZScmMN2/5LqGfthjo=,tag:HkCCr7GvG6Rk/R7xwCOR6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0M01ja3dydDJGemRzWi8x
            cnZFeElTQ3lUTkJiSGpGa2VnSVVib2lrL2tZCklDL2tyOEw0b2k4bUM4M3BYZkd1
            YWpHUVV1N1VrOTNJZ25EVDA2NmFBUG8KLS0tIHhYYk9BU3RLcE9mYmsvNUZpZmV4
            TWhnOVdWZXNIS216Z1F1ZzZhdnl2dTgK1WwE2iIrVYmK1ZRxM61VnIMYD8T8igRE
            2+YsLVMoqPZGEEAGEMjzViQrbkQaHHgil066JckRoVRAZY/LF2pBIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVnRjd1JUbVRvdDlUbXNv
            UldoY2N1U1dLU0xwTmxrZUdFR0FPTTRkNjN3CklzRkZzVjdJYlFvSVhsb0F4RUJ1
            MmpmbU43K3g2RWxkRitoVzdoM2RUVUEKLS0tIFRuaXQ5Ry9Od2lVU1ZVYVB1RDlB
            MVdmODJLRXVvdi9Pc3JMMlFWYnA1NmsKWfo+UuXp0BnNyrmhCkvuNEnWLQrAvocA
            3klwnqP5MKb1Z9h8OdLN6h8yzQdmS8hkItzgo/+DzU7IktPT4vhnjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T02:23:22Z"
    mac: ENC[AES256_GCM,data:9DKKzrK8CF/dI0xCCrXz1s+/npSpjwkNn51BkNzRlhs6Ae/SsiucW2XkkSaGQZw0kRvsGhqKisWwq2L9epRLwAdwbhgtZZZ8SY3nGhmdVNph5nukaa6dayGTRoC2vuyVSR17jxOLrVl7cTNOBmV9Q041Pr99AD/HTEurvseRKSY=,iv:8Giu+fFZZBJ4pqL9BVVVVuUUriEboikuf8EHinZNFn0=,tag:Vz9resZClkozzQiJ2mLbqQ==,type:str]
    version: 3.13.1
