---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: romm-db
  namespace: romm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: romm-db
  template:
    metadata:
      labels:
        app: romm-db
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: hyperion
      containers:
        - name: mariadb
          image: mariadb:11.4
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "8bedd00edbd2a635ef483a641014c43b"
            - name: MARIADB_DATABASE
              value: romm
            - name: MARIADB_USER
              value: romm-user
            - name: MARIADB_PASSWORD
              value: "8bedd00edbd2a635ef483a641014c43b"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          startupProbe:
            exec:
              command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: romm-mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: romm-db
  namespace: romm
spec:
  selector:
    app: romm-db
  ports:
    - port: 3306
      targetPort: 3306
