apiVersion: v1
kind: Secret
metadata:
    name: romm-oidc
    namespace: romm
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:t51LfmnoIiUQSrUKkZjCGtA7medU4R3RS8RgJTGc9cV5YDdm1bwKQeGdGQkhoHKI,iv:Ys+olWF2MBRdEXX/IpRfdSYAWXBJfihB/f5hn5JlIy0=,tag:Oft2qkRbIdvrH0v5LzpN8g==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:iuchwJRTZVzfVolkoBBHoKmZLWUlbjJpch/Ne1hH7iwqVZdHDNGGSnvlSNNkA1JYUmL5ngCaiwW6KnI28ldiHtXEMftG0oHHF2Qji2Cw8cIKmM96OncE7tDI0tEaC32K,iv:ElsnznyMRO3sLMn6oJs9CtT0E7aIj903oUkHamaG+Sg=,tag:xblv9ETe5nscTgVR4EkNjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UTlGNzZOcW40dFExQWlv
            Zm9iQy9kT2tuY0pVQkU5ZTdFOExyZTg1ZTFVClRYdHBJOTJFT1RLWTdnUi9KaVVo
            YXVGdHl4cjZlV2FFdFN1b0E3MzdoMTQKLS0tIGlYNGRjNXI3eEFOSWp5U1JjVDNh
            VVBlTWM3dEg5YVc1WS95a3ZJZWU3a00KZy24TWZdLiQyaHB8UVpiDvcojdBWLNaU
            ni72wkplVre4ncQ5rTUXiVRAwV9u3uMNnyvpzgYAsK6ep7HjxIT/pg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSlVhaFdWRHRaY3NHZG5s
            MHBsTGJWWlp4L1pwSmd1d2wySFdaK21FUkRZCmJlQmdpaGFMOUUxSXZCQjNUODda
            NzZNT1FIOStmaVphSVlkOFdSRyswN0kKLS0tIFZBb3FEQzdKRmtocXMvTHN2OHhN
            d2dXakg5R2gxYmhDMEIvQkZ4RzFEbWsKVfWqVoopIPM9XKEXQzKxhqsCOq3TmpOr
            EhWR/QmivObe32d3d0Kz8ceqqsAXHN3H+cayMTTw/Tdro3YG/EE2Kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T21:40:56Z"
    mac: ENC[AES256_GCM,data:pqfmIzatPhAsJNhn6BscuBxraHVr0+NclGBD8sHK4dk6wlZhQcqZWwgtmuu6hC246juaXviGwOnqk/hze8PYIAvTHahW+zZtku7f/Sqv216kbEdkXzrh1s/PbFkgQXJag87uRtJf1g7qZlMdKikRQHGy0HTmj7PXdHO8X/nHu3A=,iv:1oRrz/TZ+ArKxAaAwwdmtVp8vWaorT2ff+qHO8RMDsk=,tag:dUUdjtNN2/Guio/mTMxSIg==,type:str]
    version: 3.13.3
