apiVersion: v1
kind: Secret
metadata:
    name: youtarr-secret
    namespace: media
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:uehqRM0tAw==,iv:jFLYjf+oVisWz4WoOmJbBjkL9IbHgril2PP+VZkUCNo=,tag:JJxj9mojd57DjEzdOREPoA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:+M8xmDczKUOlI+H94nhVFppzCdM5NL8GwETCEsET7LQ=,iv:WxOPOZL2SrCxzKS6MyQ9cXbx4sI36HtBPzSc1cd/awo=,tag:R0aBLVLJQTSB4FcqsF2Hlg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:5Wsz4sXsgw==,iv:y7Lc1d1hL5uO3ik0H/bUtAgoHxrpj+HZChMnJtAsD6c=,tag:X6j1dVAfr/CWpDkW/tcWJQ==,type:str]
    MARIADB_USER: ENC[AES256_GCM,data:VZGnYQ+tow==,iv:WFBKbnqp/KIIe/mXnsyaXjUaeJXfYSO82GzTKbtnNko=,tag:T5pPi+4mBHL2mNEL46uArg==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:x9pAclMj3Stfua8o1sMeTrOdkmZP/LGgew7X8t9bM54=,iv:OZQJpOBf5n87I8FTB76d6kGeTOTYA46bE9G4iew5kI0=,tag:ppcqqTLRUCk0kIH7oQZftg==,type:str]
    MARIADB_DATABASE: ENC[AES256_GCM,data:Sx9+HIk6MA==,iv:pVTaeythrCuDeqgyN5+BESn/jhc4S7T+aqYw0/rULb0=,tag:NCpucAZq/gbU0xTqasbIyA==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:gSw/UGUR7/OPmP0r9bCEeElX6cwH/Ggu3KlFu6EaEd0=,iv:D1IIUN5OyBEZOdUw1Nn7/w0Zb/Kmwe+PO/6de9/ISEU=,tag:Y6kgKESfj607nYUdoP3Smw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5L2liTE1WSk1NSzBMS21X
            cXB3SHA3d3lZYlBOaWRpc293R3B2YzFCZ2prCmZuY1J0c21QdlQ3RWUydEh1aVJS
            eGxaK3JDSTZEbHNlUjJzMFRUeE1MUEEKLS0tIG45YmdLRUdGWXVUOEoybHdhVS9n
            TUtZb3Z4dDFweUlzOXhWdzFKUHBOZGcKOY5eNXZVDavh/NOa/4qWqR/DUz0RKD1V
            8xARqHzzs5PmfOj1R/j2rUMIZMg1FP0QcB8RBijg0YI1pmQTo3ZFcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SEVaN1F5SG0vOTZzcnd2
            c2lTWHExYVE2b0tGZUNWN3JQeEl1REZZR2lNCkxjSUdTWU01aDRvZTZNcytEN3dt
            QlpINytmQkh1Q09vOS94SmV3cUdVZzgKLS0tIEhtaUx3QUUzWmpVc09PSlBPWFVh
            QmlSNXdMd1I1Q2pVQmE0ay9Xbnpac3cKclOUjikQkT95F1358W3SMwgA9IVIVKzi
            vCGujlOYXYw36AIqZ4cf0DQl+6xHOOpwncw49xKblz4tN1qxHW00PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T01:40:52Z"
    mac: ENC[AES256_GCM,data:Kq2cus0sP4CXRMQzidBW5zzXBh++lRsVkdzwqL2CjxvsCJFS9M8RylAsQvNj7amui+urBT2mdSYxA+ac3LnrYJjb1aqt37H4JCp9oOtuIBobpjqHkEEPPmP92zg479/lX7Y3/PXD5m10KbHFlE/wuA+LfhscevbImtim3cRR5e4=,iv:ib7c2Z5kFwe2SCFqJ8NrH7R5jy5V2VZJltYD/yU758E=,tag:fsUZN1A/jvU5d3uKCQ63xQ==,type:str]
    version: 3.13.1
