apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
    namespace: media
type: Opaque
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:0BhYgI7TNpciWFtWpKejXxKMUUeDtnnsmpIBpiKmk5w=,iv:5PTjX5TcvPJYaYHjEc0K58SRoUNtJ+vvJDVnd8d+7fk=,tag:6qXy3S3vU1QOA2AV6JHSTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZm9qVW1qR2dVY1J0U3pp
            RzhJZmR3cnJVdEhod0l3SFR0RDVONVppR3cwCmJqQlJKTGFPeTZDeDRpeCtPNXhY
            VTNVWTQrTFc2ZlNFZTVtRDdmM01aTEEKLS0tIFVNRTd4WjJtS3RVVGF3L3k4dHlG
            SnVBZTQzNWFlS0hEZ1ZjK0tDR3pUekkKI/tPessnWdJYDundQdBoWHRIsK62XvDi
            95fa2Olg4E0v4z+haHeR3fH0YV7HqKZtjXApPzM60liPtQrwIApshQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU25sOXRWY1lpclBmdGlz
            aTVLbDQra0ZTQkN0VThFK2V0clRaTll0bWxBCk52cEk2Mjc0ZGQvbnY5MGtmQnh3
            MjM2d09UWXY5MlFjWW5CbldKbHlhZmMKLS0tIGFFSXJacXBqMlVBWmVvL3M3clZs
            MDRBSFpDQ3o5QUltOXNxWklGRHQydVUKEcs0rs3x8I6aIyiGxngYAoPPalJ/l3nu
            0OW1peFs1MMeo62sxGLcwWTFrgzX8S/or2GKTs3+dGTuv8YQo7dqJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T00:09:43Z"
    mac: ENC[AES256_GCM,data:xmyPLkhiVRMF7EB91KhspmQesVXQ8VMDEGL+YS6p30s3C2rKNdhcU93dvaKdFI399QLgdmU7RDz2LY/ocB/wRq0oIq4V7RIPlGDi95q8seiBCiYMyWFUps368H3NXRAPdi0jmQlgLMvupcDp/O2EOMORrSjVslV61QipIUHdu3M=,iv:cgmmmTuEzngEADt9+08dCfDgcsD1hw7hVDg1c0Snvnk=,tag:d2q1klWgUmnfsNSMgZqmsQ==,type:str]
    version: 3.13.1
