apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
  annotations:
    metallb.io/loadBalancerIPs: 192.168.10.55
spec:
  type: LoadBalancer
  selector: { app: prowlarr }
  ports:
    - { name: http, port: 9696, targetPort: 9696 }
