apiVersion: v1
kind: Secret
metadata:
    name: jeeves-deepseek
    namespace: jeeves
type: Opaque
data:
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:Zavh3snp6JqDqZmbbKy8kn2ruoIhgPaEzpQa7yRuOl20O5EslsqXlA0cw49xcfV0,iv:JR5vXXy9IoBFENEGyGn7SkrgyXUWVXCgC9c3hoXDo+U=,tag:FhGgKok3dgmFaK6e3GZnjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNkZQcTN5T21zYVZQT1Vp
            a1Y1WGxhRGd5b1VkL3lJRGVpamtjTFd3MGk0CmdXTnpyRGQ1Tnp2eEpVTGwxLzc1
            SnZPMU14SGVCcmhabGdJR3pDd3MrOFEKLS0tIDM5Vkg1ZGVTUGpQV1piN3hIZHJs
            TFVrbVJ5cGdDSElaYXUzSEJoQlhWam8K7ld8oWlmkvhO4O92zi4UouDzgkqy+DDu
            +lRTS22QSvZTX2F0vJfwAta/azg0Q3UZp0pXpXewCR5gPqPLtYkXVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvU1lCVGNVZ3o3dlVyTmg4
            dDhXOTlhWFZOMTNJUjQ4UG9wUUJCQUZtNFYwCjFvQlRkbElTRU52dFkxbVRKK2V3
            U3ZoZk9vbkd4aGJGS0RxOEdTdTdXOG8KLS0tIEx4VEFtZVZhOTc2dnVycjRnYWov
            Tm4wNGpTUTdmMVFxRmViUkkwYnE0ZDQK0gB/NxqedwSlXKhr4IzYR1g1ib35x7nu
            LISklQft8hH1FVt5AZyErF4rFfbv6SaugUMqs4QCg8z01s6pLs5Agg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T20:28:10Z"
    mac: ENC[AES256_GCM,data:T31/EbbjQZBaLkNV4g14qkXPeVg0eZ1IU7uYRZ1nx8JG5Ra/hHPAKtvjPGkysv9/auCpnO5T0zvG/4WrVCxA5b8d9VOJKoRc1vye/TZ+3YRX6OUBYvw1W10PQXQlGRRNy+Ja/n9E4l4tKA0NJzJ6SWusxy+9K0wEEy3SJByIqZc=,iv:Hx5Jf3h9hsZ2NCBwhv10wM6M4/rz7ELTUufpJmcV29k=,tag:0R2JKxrAEPG0Yryv+qS9aQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
