apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jeeves
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - config.yaml
  - nginx-proxy.yaml
  - dashboard-auth.sops.yaml
  - shared.sops.yaml
  - deepseek.sops.yaml
  # - discord.yaml  # disabled until token provided
