apiVersion: v1
kind: Secret
metadata:
    name: hermes-deepseek
    namespace: hermes
type: Opaque
stringData:
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:rSB7Fzk8IYozz1r+KDpNvd02cPycNsVqa1mrKyEClhSAa8M=,iv:tETvT6AmS/cb9Ewo167iWB0Z2Cc0lTmmgTmtTIIZkcg=,tag:v9sOGn4lbv1ypO3eip723g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQkFLYmJhZFMxMVNGRTUr
            R2ZpZmZZSGxmMi90NThZN2o3MEFzbHBsSmg4CmNRMFpGWi80RC9wSG95Rmc4NzVQ
            M05FREhTd0N2anp6Ly9memY4VWdUVEUKLS0tIEZZdzB4MllZSGJOOE1zdjhBWjdo
            cXJ3aVhMbFNrK1BySDFSWHVrbnM1V1UKalmHYMTJFroD6ijf0PxmQuB+QxjhlxHp
            ARoxCvX26EevFGEzwcPkLiWFnNF9yiCcctWWvJGnqsZEZBC6nm6N5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaUY0NXVCMlJmWkRzTjF1
            V1hLNlpzVFp0Q1ZuT2xraHUzakx6WHo1STBnCkJwcUlVNkhqYlh4a0xubFg5cVUz
            eC9NV1VnaFhONzgyU1VscXQ1ZDhZZ1UKLS0tIFlhbm1NSzlyallRVld5MkJuem1p
            L2NZVDkrcHBkQWxZS2xXRnpHVFU5dWsKSZDRK8rRyFLx+V+BuygBXbJ3aLSHsQE3
            y5C33Tj3w2AxU/SDfAmfmibIIkbqR2gmynkRVo5BFp0aGoVQAsc6Sw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T08:14:02Z"
    mac: ENC[AES256_GCM,data:Vq8p9GMG0C3ikTwBr+IGTocqofILZVgUnKg85haMFDyunGD3FQdM3Ueo3HXQ3CG1Y9CEb/6esoy4UHp/8E5GK50d2ienoIRAv8CUfYRCSJaqKXD/WP/1/PgAbbkWrqgIwED2kMaFcYzfalLUC+Jp5HYGWigM15VfXUZVtsiD/cA=,iv:0atiLnsKUiS4p7I7K7xJys/a8bPqgiQcn2zySiQW7AY=,tag:uXWcCTrtgenEh70BRzZQyw==,type:str]
    version: 3.13.1
