apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: media
type: Opaque
stringData:
    #ENC[AES256_GCM,data:7ta9ykXoaHlmdEL0QmAMrFJDuY9ERK7QCJuqgqAe1ik+mYBgtL/GOULU,iv:dRwm94w88brQ6p8I+b8Ys5ih30cP7aguzmoKXq2gWRI=,tag:pIZQ0Br9SlS+I4BAdA8p2g==,type:comment]
    #ENC[AES256_GCM,data:qQrXzy/mI/e1jYFFrjxPyalQlfMNY7zlldu+/hvD75GhRi/5YvYoNiqBeWIFBw41pjld+Iwnvn6BbsJ6X7nBuWV3jnj2i1Ej+MwlNikoFbLzrYqzapJ5XiDoNQ==,iv:GiWI9NZjchrWl0OvsXL0GQqx2mSqR9GiG73PkdlpuoE=,tag:TQZDiOLCtGiEQeCLA3nRUQ==,type:comment]
    DB_PASSWORD: ENC[AES256_GCM,data:hux+TeR+OWV/boAarIRSsSB2Mw==,iv:o8Maut+wPNHyhsLC0b+xZNbilG4Ntxs1CGWiA9M+Plc=,tag:ofQrjAD0bp1S7P2ulwwk/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNGY0UG5yQUtvNUhYTlJz
            eFRZbFNjSG02MW1yTUhvZHQvcFNxSWc2N3k4CnRCVlVPZVdkSm82dk5qYVJKeWxm
            YlR5NXQ0RnJMUG50Y3lJS2J2VXNxYUEKLS0tIGFOT1JZZDY2U0RsRjlKVWM4ZGdi
            SGlTamtTNmlEYngwOVdLR040OXVqY00KZCwX2smePK1PhLnGykxb94NjNrPZFQ7A
            NL5mF7PSgIYcTNAgeF/Lbq/cBkFJ7S2DdOjvdB9wfZUgQtcI3T4Wkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRkxxWm1CSko1eTNYTXd1
            a01jNTdJQWFVeXliR3gxQzJRblE0UTJDYWdnCmx0ZUpFeDd4bXhLdnpnc2FwdjFW
            QTFhdlMxSmJRWjBnL21sRjgvMEh4dEEKLS0tIFpPK3F4Z3Y3R0JIMTB0K2RVWUJ0
            OVFlTTNZSzAxV0ErVmhnVExFOFRpa0kKqp5/L8HTiJ4UBvHsWEUEjdVz1IaU0kVg
            VvGW7CU9fgNlPdA999jj8qHCdlFm4yVQ5Stox4CY9EmL8HBsZPuEnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T21:41:48Z"
    mac: ENC[AES256_GCM,data:FUbDWuV8+HYwiJtzOUEpUdV8cjxaKpPmgqS8/UuvHjO/bw5LVY8FvRoaQLrxsPN44UDys5u4q4wZBwbzGkEluPO0SzMxNxKKtetMxHi5p3KbAscYXZbxGU6dtxQgGDq0zvkYHevBSKRinMsir60lvEMPnZfB07MyRKh62cV/tUc=,iv:v8bTzH6xlcjGBEsez4+XXatNDxrL9u1Sgplj3v5URu4=,tag:A+kgztY/KZRDJdQOhBldKQ==,type:str]
    version: 3.13.3
