apiVersion: v1
kind: Secret
metadata:
    name: lidarr-secret
    namespace: media
type: Opaque
stringData:
    LIDARR__AUTH__APIKEY: ENC[AES256_GCM,data:lkPVy39t27cIsh4hicN1VEF9BDT6VnG3bvrWQqBZlFg=,iv:Rq1puhPrdgKwTobgrrWe6qJrtE++4TwxGOj7F27ohSk=,tag:f9nqYRCU864DkAhT4IWTsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmT2Y1YjBvUjZmQVB3cjh1
            Z21RbzY5KzF2WFRmQnRFMTJhSnlvMko0N1I0Ck1IeHQ3U0lOSUMwZDVwTE85R3Ra
            OGZ6U1VRVG1naVdOMTR5Rk5NMFhGWFUKLS0tIC80VVRDQUExZ0xQbjhRZU1wYVp4
            aks3NllxNGVXOXJWcU80QmtRUFc4QzgKrXH1O96BOR212IVh6T5GsnFoIdsXH1KI
            d1Sa/hlA+M0Ky93zxVemH7Qs/Ng4sCzciw4L5M7yocO3iIEyF/fupw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRkVQeHY2UmV3aWlDM3Q1
            eVRycXhnTG9QOWtUd2NzdHJjSXNYRGFyTGdrCkxKa05hSVR1K3l3RHBxVTdjMStX
            U0h1akdMU2VRazJDdS92clZ3V2NIdE0KLS0tIDV2NkVONTQ4ZmQ4eERZdkdaUnpt
            UG1BZlh0dFZFRndVNDQ2WEx6aTdIVFUKB1tUSFvbc6oDCgLxWODwd5W/FLlXvoSy
            EeIqxfKSE12g8gfqaHql+nvAyxSXl9OJYE0Ysl1cMRIrehsqCl4cGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T01:47:06Z"
    mac: ENC[AES256_GCM,data:2jcUbwrXkc2OuqOmJWgnX54nVnUt91IAGCPMBp3rnhp+mjyTWVh6VB8ktHc7sKVsf/rcQJHsY3oPpB3DeyxbOHX5qStu5U+GxHTvLOx4mc5IPEEc91ZCYzuabyzBPgq4EFhvAxrEglF85ZyZ4JHbDkyOoxrHnUis4vKSGwEFlAQ=,iv:bDqwG9zy3YfVTo2n1/AEk1VSecsCAuNIFIYR/mYy1JQ=,tag:FV3J481YA0owVpIPo3rTmQ==,type:str]
    version: 3.13.1
