apiVersion: v1
kind: Secret
metadata:
    name: homarr-secret
    namespace: media
type: Opaque
stringData:
    SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:eKUcUz0zt6S/wM2BPVvZq3Y7y7DUZ3jlS9X1BVElUwaiA1lBqVObqNdYwu+bfyNQM+wvtKXAdiYhmbxPBKH8bA==,iv:lKKih5/lesdAVVeTqZSNqP/kFwkzfswVzV3/dBth5ro=,tag:V4tkV1PQ6nmfX/JUbAdneA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MEFod0s0U3FWU0xiTEJj
            WFVLNWZ5S1VxQUtYbkQ2RzkwdzZsWGxQU1UwCjE5Y0FZTUZWZDNyaGVRWWkrRjVw
            cDhqT2l2UzRKZklRcGVFR1ZmSFNpSXMKLS0tIEx3RnQ2dWxLdTd2NHZZUFBVeW9k
            dFJxbkNNZ29EWk5pNU5idXZjWnZydFkKZb4C6w9MybY8g32dbYeCx1Ae3RjqW4WV
            7i9/wZHeRcZ16xlXiapjP1QEe/Ag9BI6hTXAZywGa4xG3ZuAgxw9XA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvK2htMkZDTVd2ZGFHbFhv
            NlY2ZkJwUHFxaG5pTUI3R1VsYnB5dWVKdHhzCm1uM1E4QWdaUU9NbHZ5VzZlS3FX
            eUxEYitCc3c2cTdkRlRmUUtZZnBPVUUKLS0tIEVQaTk3Q0VJQkZTMW9aYzUvTElD
            aHhubDlidTU4VVN5VTJTSGtsMkF5RkUKBCnfWtK2r8hJzc6i09qxT2GUKTmaupSt
            SxLj6ltxoC4xhf+t5B8lS720Vt3iDwYG+Nxisf/i1i6dzZvoCBDFFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T01:40:52Z"
    mac: ENC[AES256_GCM,data:Ev1a2olFGdTv4TyEd4bnzqA6D9g5fEpX1jBnHLxnpbtFAZ7FF49EVDyfhu3zMGP/5WYJ91FpHKQKzSLxqTumXr0x8J8tSMThO07bwFoV+aRyVQdEvn2joE5y/SisF0E0uUKmbqVhng9X3b34CzP77UWCrJRh4yG3c8AX0NYBUl8=,iv:e1zjVO1tPf0L9M2H5UOmPFOwgPEHO5HRPnwiHkgHCMM=,tag:UoKvs5WeN/2GLbOMj7UjKA==,type:str]
    version: 3.13.1
