apiVersion: v1
kind: Service
metadata:
  name: homarr
  namespace: media
  annotations:
    metallb.io/loadBalancerIPs: 192.168.10.53
spec:
  type: LoadBalancer
  selector: { app: homarr }
  ports:
    - { name: http, port: 7575, targetPort: 7575 }
    - { name: web,  port: 80,   targetPort: 7575 }   # bare http://homarr.lab
