apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: media
  annotations:
    metallb.io/loadBalancerIPs: 192.168.10.66
spec:
  type: LoadBalancer
  selector: { app: navidrome }
  ports:
    - { name: http, port: 4533, targetPort: 4533 }
    - { name: web,  port: 80,   targetPort: 4533 }   # bare http://navidrome.lab
