apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: media
type: Opaque
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:RGYpJf1TgGcMoNYfaZe+LBCdkgCYiw0J7ddGptqZCgg=,iv:jJnVn3Iq8Cd+dBBM/5D1hjvuFdeDGipj1ScGlLVI2eg=,tag:bR/p+uEH+A3HRqHanLMCbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYzhVZ3RoMUxZYXp5SExO
            VnRHUUxjc09ZQ0NwckR2U0g3L2JHZFhpQjBnCnFyNnZ0MkFiQXhtMTBzMVlPRmty
            OWhKdDVRNGZnRzFjdjM3YjRFWHowaTAKLS0tIHpnMWpxRy94d2hPQTlFNWc1emgv
            WDdkSU5leG1BY04wWllrNS9tNmlTaGsK0hFGacHoJKNJ8GL6cdffGF6Qwa80anq5
            2YhnT3nWtb4Yu6UOxLXeWYn8mP4d5XfRA65TL7bai2AegRw7pcbQCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MjFqZHcyNzhDUkdsQXFn
            elVCcTd3dGZURitmK08ray9jQTE1TTg0UGxNClprZ2VsNjMrMXA5WC9Ic2NnNndy
            bkJPSVJ6R3NnTHZxQklGUWNkbVQybU0KLS0tIDJxTHU4MDFXUDhpTlNTN1BwOWxH
            cHRpYm1iQlIwT3EyN3pxeXRzZWRpRGcKbD0d+Y6z6PBzzDMh/qQl+bbyVf0mTkUM
            OkXvTJ5Q0hTY4lorbeEVsKXxPYBcr5MaIcI5skaypMD/JJIkgccHSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T00:09:43Z"
    mac: ENC[AES256_GCM,data:U/zAoglLwr7UDeTxyz8RZJ1M1Tlh5Gt3MePuPrCOS5NNIVYcoEdXkGFPpRwtP48zWngfaRNINOVG5BZ3DOmBIuq+kJTmvcuOpKOoZiG8pwKgYn5Z6j2BzMN8QSHDo16+NNSdRhg4vlru3c3ImhSuMZ+YumJw2ZuA0zwQVvCYeYg=,iv:sg6kC468QC/4AELISanWGDUC/wnDKeQa9yekyfvTntw=,tag:09Kk5AFfb7NZlaLi1YSyHw==,type:str]
    version: 3.13.1
