apiVersion: v1
kind: Service
metadata:
  name: mqtt-explorer
  namespace: mosquitto
  annotations:
    metallb.io/loadBalancerIPs: 192.168.10.81
spec:
  type: LoadBalancer
  selector:
    app: mqtt-explorer
  ports:
    - name: http
      port: 80
      targetPort: 80
