apiVersion: v1
kind: Secret
metadata:
    name: seerr-secret
    namespace: media
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:/MOzPhKV8/IpMx3/Z/8SbhqIxdvHGadgk0ThPoSVXeqmJYLLqgHBWntcTKDwtzdFSm59sqk2a9eQ9n6xb8KJHA==,iv:/nCJpf1A/Hfo/yXJkI6fmsUfgtMwG8vHdxP/ipCO81U=,tag:rSowIjg9/3sTNJ0PBvyYJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSGJ1Wi9tV0EzcFc0N0F0
            SEpTckdMblV2eDRnbGtvbDI2Q2crRENBL0RNCjROVFhJTThnUDdZT3Btb01GWlhW
            TFNNb2ptMUcyM1dwbkxGV2dDNDJlUDgKLS0tIEZ1NzY3QUlrSDZSNjRidXFWQ0M2
            cGhrYUFUMmU4UGw5NkxZcWZ3cnB0Zk0Ks96nNPu6+yBr7Kkjpii2K+RvCNDvTp04
            cCKr3zUxECOryMqP4+TvgT7xsMQzn8XdS1PCj1tNKrfp77Xl3Ftz8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZmRFQW1KVGYyZFBhbEFU
            eUhXYUd5SlFDM1dWak1Na0hhWnlPdlJGZ0NNClZZNlNaVVZzOFZkZ3lJUEhHSHlL
            YWtHWUxTT0lnbFFibUZBSFd2VWl4OWcKLS0tIEx5WGk0OExrMXlGQ2I4UTNlZW5E
            RU9xZVpSMjN0b1k0SUp6L1NLM3FwdnMKRkiy3+nFxX5xxenj0zxVomGbK8pUz+vh
            ujRCHFE6bUWn6gCoHd/zv7a+4W6i0apRoltqqqwOhULFteIq58tNhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T01:40:52Z"
    mac: ENC[AES256_GCM,data:GgThNgSwFHS5qG7mFTceU9eFvtUrX/Z2TLmls1Z+BT1sarZQFlv9akHnCFMr/K0PP6Ue5eUETbfsqGSO0+TvEDzEHqg6kWcN19sKzCaPfV1ZN26vnihXFaXFA6nOaSmGqW0MtFFwrd7G8jVxY+35uO0NElbUbe2KW0MjGewJ7i8=,iv:qaiQ7aUCQFg1S+H5FYkrWNOKxsRsR/N1I81b/d8LgQ0=,tag:DnCb49cM2reOp6jv9+PLcw==,type:str]
    version: 3.13.1
