apiVersion: v1
kind: Service
metadata:
  name: homelable
  namespace: homelable
  annotations: { metallb.io/loadBalancerIPs: 192.168.10.89 }
spec:
  type: LoadBalancer
  selector: { app: homelable-frontend }
  ports:
    - { name: http, port: 80, targetPort: 80 }
