apiVersion: v1
kind: Secret
metadata:
    name: homelable-secret
    namespace: homelable
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:TPJ1R3Rjm4rFLR5LhY/nZxZWEMjezy0emWD+GzAOwRhVchZ19Z49en3qNrWszHCKOz2pgolaGFW/iJMwZAo6NA==,iv:RzI5Nw3OUJObUqpKKI8t0UXoSzJbrzwKkUu8xGuRKFk=,tag:UUIEqn5Ffr2PsxwilesQLQ==,type:str]
    AUTH_PASSWORD_HASH: ENC[AES256_GCM,data:x6Hidq8r3I1h3TAqbPPPVlIDzbTE2r/WVElUH2GbZzo+HVLZIPS41CNyDPk7IwEI6EFQ6QL6W18SMxLp,iv:5cM+ts8AEo1BUYapo8w030g1aAw/utVbwld/lkSyufk=,tag:fB7TQe9da6dSD9ZYOvIGig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcVB0dEVhcXYxRDN3UmZ3
            ZVBDa01ad0l3RHdIZ2Vhc3FDQ2JhK1ZPOW5RCnYwL3RLQ2ZZWlp4VlUvMGlGaXhp
            L1VhWWllSU4xeDRxLzRna0JQNHBDTFkKLS0tIEJ4T3FIWm1sMzBUQ05hU1FKZWVP
            eEUrVnp4REkvNWMwM0YyaFVhU2c5bjgKG51Sy/YdmY+a7lVkafRgOyH97e86YgxS
            DrPD5SobggWzRGD4JCKgWSChhvWMMlEG1vgC63cFm3IUVHIlz52YEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKM2RTWXpWSk9yaSt4QzFz
            ZDRlZFFvU04wK2VHa0RVMVF2NjQycHlvMUI0CmczclVyTmJSV1k1N0l6WHJJYlVV
            clNFL2ZwSVVpdFVWWE54elpYZUw3SnMKLS0tIC84aDMydmpSRVlyT3F2UDVVV1hJ
            Zi9nL0lFYjJOeEtSc21UbEk2c0dvZm8KQX/DIEZ2T1FjGIR6zeG0eda5e3kkgO1P
            FIaRVEcMXimHAaYjqM7zBI3HVLNsjdPhv0EMQY8/CEFjZ1A4Nf7c0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T07:07:27Z"
    mac: ENC[AES256_GCM,data:cYxcFVcV0QtnG2c010nq35dzVms8aXkWrbU5JyqJHo16Vg3MHuHmBRK7XPHDuJrhlh1VoVvHnrrIZ0YEfJddx6P76uipiL8jq3SCZx4UwS8OJFItivsGLmaWK9//PcQGhKJ+Wdml26EvG5mLJT6JiAFBf9tmJ4bekJd2Uc0uY5s=,iv:cd3IMG2XHDQ7qGHachakmRjemFW4DPekY4e2cU4FgTQ=,tag:F9dgEOsfR/BfiEx9tGzTEw==,type:str]
    version: 3.13.3
