apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-caldera-data
  namespace: agent-caldera
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
