apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-caldera-vault
  namespace: agent-caldera
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
