apiVersion: v1
kind: Secret
metadata:
    name: agent-caldera-secrets
    namespace: agent-caldera
type: Opaque
data:
    CALDERA_API_KEYS: ENC[AES256_GCM,data:ognPzE8OKTvuR/BDjs3CUYkwOvRjRM5G64F2+l/1qY1flk+x7HFHShxnkcMglKviyPDAU4z9SQb2mSIRy9l+GzCC5NitX8AziKZCWqR7K5Yok3Efpc1E7A==,iv:EYwFrrLI2MuTEuB5pOeNcT8LLDraEBQtFGSiFufa+4M=,tag:ZHlyqhC8UjHShykZuGjwMg==,type:str]
    CALDERA_GITHUB_TOKEN: ENC[AES256_GCM,data:eIcJdueWsjSw+YNiNdmGPioUjI65Q4iPfxhZnOdb70oL9M+xFcDGlgbeA8LrVFwxPPeSVhy+ZpU=,iv:+ROt3JgXq9nEdw7w9AyxOPhmGt4dURjCJOzAE1YIl6s=,tag:U4QzNonu+5VABnYw3tP9KQ==,type:str]
    CALDERA_WEBHOOK_SECRET: ENC[AES256_GCM,data:w0yy6EoABImIOcDZa91q8bA3gZjljAMpFiNVcoZ/tkZy7Shmyuw6WDM4kmaRfTxFjGYlh1bQLqgp3HXsX/b3Hdo8TSfTRLPPkHkPAMSNhpeq3JytKUPdtw==,iv:4gkDee4YAm+c2c/YNlX0FfvIUvIMD0grckcZRF7vGuI=,tag:PHuahpSb9aA7NvgASars7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycXJUcUdnRHlNcUVSMk1x
            M3QvWGhwMVNkYytYTFhjdVVoak5yNzFtQ0UwCmgyc2JRQmx5c3Y3ZjBiWW1lRTdn
            Q1BqWTV5QndxM1I0TGpGRmJhdzZESkUKLS0tIGlqNU9lSlo5SlFHS3RFUWZXQmZ0
            NTMxNUgvUmZmVVFXWkVoSVZpZHlkcVkKbXiJwf+VQOFYwcO8S7vN/TX5NEpJ3iTQ
            GuiR/Zj3BUN+Vre3XtuWo5sPAZm5RteA2SS6yniKQlD5/2aY/c8ZeQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3L3MwVk90Q3dBRm54TTF5
            WWRaa1ByY3lZNkZqZnljSnZ6T21RaEVGeUNRCk4wRGEwMmtsQW9lUEFmZjJQUnp6
            MW5qZWc1eURzOHErTm1CdGxXdEp3a3cKLS0tIDZCU1hwK2hvRWQzaDZYYWJwZTR1
            QlUrU0hkSWUxbGw0cVprYVAwb0JuckUK6OOhenELTocTX66REj8fIoCDEyDgqPaS
            jtm4n7tYwsbF05tfIoLsr9Ih5gKwC7uKpuvssi6RHyBKA2VseqydXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T20:28:10Z"
    mac: ENC[AES256_GCM,data:qu3tYuJVpznK0huffSx7NZxu6O7qI02Ih8Kua9S3NnqXIkt0//usXf3GLHI7MMfKb0lDHSXjzx3Bo6idmPenOYhagpyWVl7irgQ8pDoYTW5cpzvGqtn/A+RLaNiSiLo2HcG2CKBQl3VsW37LN1aE1xEGCOaL4eOTbtYR5A2M6P8=,iv:tcZyVLjvZTHMKj8ZjrwhQjpptyqEDRkePnXzLxidXp8=,tag:nEUp+Pu+wbKhzoo6PFw8ZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
