apiVersion: ENC[AES256_GCM,data:EnQ=,iv:ZzDIayEGgOECE5ZtxXw4fsHwvp4ywGlmZYMJIWQMSQY=,tag:R41Gy0KIrHyXwLlhQPpCLA==,type:str]
kind: ENC[AES256_GCM,data:Lsalg+GK,iv:McV6qsiBT5z3uDb+qivne5pQw0wdJTK8ordAQoQfhY8=,tag:aut7yqOcMn3fWLQOjZzcuA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gM8rm2r4z9Lk5RWVcOJqWc+j+W/j,iv:VsZXdHxOYTx9Z8umEAFjdTSDDUdBZNwsLwnKysg3A/c=,tag:XxNzAOVyW8tQochlem7YIw==,type:str]
    namespace: ENC[AES256_GCM,data:sGdk3vvr/ngfG1csyg==,iv:KAs0gL/rihYF93jH+AaFTLoon7TnYb8gfgucKdMvB1k=,tag:f29VcpoME6k2ovIiGDTC+Q==,type:str]
type: ENC[AES256_GCM,data:0I56anf9,iv:VeNhyD9qc2LtRnLWaqC9OC1iMyHrsXA6UL8zR32dWZ4=,tag:zIjW5Ov4gAvLeoRSb/Ph4Q==,type:str]
data:
    CALDERA_API_KEYS: ENC[AES256_GCM,data:6hwHw18bYTDXsDm2JF5C/JosFtO2Iy9sY3oflcjcg1+21JgkriUCfQw59IKCDPbf4Egw4F+StmszC3x/9iwhjppy0H8O8VJZmr/0tyC9CfSFnNVf+z+5Qg==,iv:ZSh/xmfyKmegjSdEkYFiWqN5m/iOy+AZzHZhKJ8bFqM=,tag:oke7rKvg0c8zdoxCpYHGWA==,type:str]
    CALDERA_GITHUB_TOKEN: ENC[AES256_GCM,data:8FETRwOWsRplCS7ourAss/lpSxksnlRpW17ncOp9+1adfeUsMWeDVBO3R8OzT3WG8lLF1HBLQZQ=,iv:a6w4mRlA1QsIoM7jf9TDmrmm3vtbXMMNnwvmX/UXnK8=,tag:M1aEE7e5mtENE/uObPLnOA==,type:str]
    CALDERA_WEBHOOK_SECRET: ENC[AES256_GCM,data:m5LMi5hJYAcHxumN5j4rtxJuTw9/PSCahvohFb0v/hOrUMmXueXr/owUAbylwqDQUCpG+vw9Bt36ueLXK2ifulS/VN9ENLSczYAzHUq2VCJVDLfQ2H95yQ==,iv:H1wjKD+U/wL/HSt752DobQqag74fDV4j+lZoGVoeWvY=,tag:nrmyotDiDRFxvIsNeiv8fA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZ2N0a3oxaXB2bmIxRjhE
            TUdpdzdCWDM0c3NkdHFZK1Y3SXd0WjB5aFVRCnVVQk5keFRoUDFYVU44bERwTTRq
            eWJoS1VvQ3Z3a2xnRi9CYXhLTHYxNlEKLS0tIGFBZUtvVmVGYXdHd2YwMFJlNndO
            SHMvYXoyR0ZrUE5EZ2Jsb21zOWpybGMKG0U0XlBPOs/pIf4BukRBbDujRIHJa3OH
            2YrFuQjEgDbVIpNyYMyRFn4HOMvjaQb9zfSgMMx6LZ2YUNAymODKXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQkNsbzh1TG5wb2lSUGZJ
            ci83ZEk4Q3ZxeWcvMS8vQS9rN1M5ZjY0U25JCnRXNmJwR3BQYXg1cXRBZ0JBajhv
            SXBteWQzVG9iblJBemU5ZWgrc3NCR28KLS0tIHk2RUJOOEFyRjZ3KzJ4U3Rjdm5H
            YW0yd25MSVFWU2I4M3QwejUzNFd1c0EKvukVaVK8P3SJNKDjn0JETvY4bV5iF7WJ
            vw3PU55MAxkofIVFI5QAKhA2b+PURS2tDeZPD9mPgUhkr7KUCfBdoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T20:12:56Z"
    mac: ENC[AES256_GCM,data:EOqG/HbcRzTGRWtdrwGcK43WE0eaWAzg91AyPUUithdFkecQXi2LUP9QBsD8gvN4b+cZnBtu4lRWyYorfNtZv+djKgy44FQHYFnk+S7ePB3XvV5D6OtrvaaUN18UHVzx35kK4lVQOrWBol6T9WEznDScVIJhL2w0GeV9x76uWZ0=,iv:G4A+Fyd0eMwDwXo2JoWcpX0dJjSppSqHDDpicZyEM8E=,tag:LGYrxW9dxbLx/1VIHc73Fg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
