apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bindarr-data
  namespace: bindarr
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
