apiVersion: v1
kind: Secret
metadata:
    name: pterodactyl-secret
    namespace: pterodactyl
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:YRvy9M21KQ59kpdkUf7nyHfg5qJqPgPN0YyZNSECpffIkiKOly2QwN/yJKphwX6a8gpL,iv:6y0owZ5S+JXFW9Lc9Hw2dvHbIWwzgHFijiX2pJIoZd0=,tag:uUg07A17AKRzHOBoGe2alw==,type:str]
    MARIADB_DATABASE: ENC[AES256_GCM,data:T4NYm7Q=,iv:nU2CwIfpxGOCxfja/xMwgs7MpdhKJomzahec+d7v0y4=,tag:23/hfV+KYgkadc3xazGmMg==,type:str]
    MARIADB_USER: ENC[AES256_GCM,data:g5tx3R+JlHZuznw=,iv:fZ6Zquc3g1t31Fk51CKjqsI2AmWhM1oDyiccLRa0Qmo=,tag:EOFawdVtBNkahVxIaM1YLw==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:jiEjZQngKR4Ee6eG5V71768BqwcfpI/Qwxf4VHPhC04=,iv:BZWDglncvJup3FWBUtq15ByXlEBzVxK1/eIcDfLPzIE=,tag:9goeHjqlh33MegH5PP6y1Q==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:w3/rcAACTVGDsVb/U6YxU08OrFvMPWJ3kzKAIG7mnQA=,iv:Qw5Whn4/sLkNhIcArVryIjK1lclEKEe0vt6mqJ4pjeM=,tag:ZOyjkyt3Pu4CEGdqdMwcBg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:+Ujw/tjXdYXKu4B6zWiLzZ0REUX0XlroCS4K0ty+2Bc=,iv:yxGx7GeS4YXi7PNLy8sdoiB0FddXIquI4Yf9dA96Go4=,tag:OqPVxMdjResz26whwGShnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWGZvRGhvOVo0cWVBK0Yw
            Ulc4RndWVFVrVnNzRnB6bjNabzQ2dUtNNXdNCkNGYmVqS2pnc0FEZmViSkRReE01
            aTV3U0QydlhQV3VFWUxURDBhaDNRY3cKLS0tIG1Yem5tM0ExSmtsQUQ0cisrR0dZ
            SWcwUlpkRGkzNWhxMldJcUp2cWlLMG8K7xHm82zSNedSnfb6JqoVJxZOJjB9Jir+
            GETZGv//g1tXJzk4JRKyAC17hbgmd99/jJKAASW9g6zRgAvvV5N7RQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSzZZNjdoSFVtWm1tMC85
            d3dMa080MlFQU3F3QURaVitNcnNEOEdUaVFZCkw2MFVVc0tBZzgyMTAyMW5XMUVm
            dmZiSHVLSXJOb3crM01mSUpGVnNrR3MKLS0tIGpZa29IUXA2R2IvZHp5RStLMTcr
            TVJnR2draTdwK3hTa0w2aHFwN2NSMnMKjsPkWkcdS1/G4wIa9UdAoKHx9mK+vJaR
            ApQYEM4FcrjwC9LKLTb90gPpGHPJktBDeidRmOoVpF7UhhzTH8wInQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T02:25:36Z"
    mac: ENC[AES256_GCM,data:Z2Me7P72Zw1/1bcskG4s0QACK8WD5XuOuookcoXJVqZzLqasXebXDdXW0MvXjrR7RI4QTmZAwS+mD2hgx6HiOZbJSruzjRjhqbDnn7SS4NcuYYkStB9X68d/I6iMG5n+UtxNHPGdf8wz8TxRBIMQdfqjg8vv4nWz4kaHP6mJAgk=,iv:ndlEbjRcZfLjfVKiPa/0zWDYe1755xsDdtjBlF9AnDA=,tag:AeIch4LIaURLtf3auQb1kQ==,type:str]
    version: 3.13.1
