apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-passwd
  namespace: mosquitto
type: Opaque
stringData:
  passwd: |
    mosquitto:$7$101$wsWluMNCquPFdLQ8$1znlwi7b1HkwITrX2VGnnxvw9TMAubM/d5Mzy8HRjeNFllidHO4PKOEGxaIqGsdzkrfNlWb+LTJ/UjI49zX5tQ==
