apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
  annotations:
    metallb.io/loadBalancerIPs: 192.168.10.72
spec:
  type: LoadBalancer
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: ws
      port: 9001
      targetPort: 9001
