apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: nextcloud
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "N12zhCzbXAkJewApbyf--TX-27_dU0sv"
  MYSQL_DATABASE: "nextcloud"
  MYSQL_USER: "nextcloud"
  MYSQL_PASSWORD: "BLHUXy97Y5gP4hJejCS7GVkFLyWUh22o"
