# Application workloads. Each app gets a Flux Kustomization here.
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 10m
  path: ./Hyperion/k8s/apps/headlamp
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: metallb-config     # needs the MetalLB pool for its LoadBalancer IP
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  interval: 10m
  path: ./Hyperion/k8s/apps/uptime-kuma
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: metallb-config
  sourceRef:
    kind: GitRepository
    name: flux-system
