# Reconciled by the root `flux-system` Kustomization. Lists the cluster's
# Flux Kustomization CRs.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure.yaml
  - apps.yaml
