debug: false
app_name: Pterodactyl
uuid: 623d73db-5a6b-460b-a5f4-0b171ca9f1ad
token_id: ENC[AES256_GCM,data:HMHwCJcZRF5J6wQaCyKYMA==,iv:F4uSbXM6vBiw5jNAnTpS8LwpQ5xnUiishFTuk24Gq0g=,tag:HCLnmhEI0oTn1UUBKjZ+Sg==,type:str]
token: ENC[AES256_GCM,data:49fb/BlDybH15/7+j5b0gfWe9FDxeUrAhadxVmSzqSd191YkBA58SZ5dyS6ymh2U8SWHY5oSZq6vbe+1vqUB0A==,iv:asv6382R0Olz/19dY7ZT0iEiiPtXJRKms97rBpo1syE=,tag:ezEA8ZJxkle3YukQu4MtRQ==,type:str]
api:
    host: 0.0.0.0
    port: 8080
    ssl:
        enabled: false
        cert: /etc/letsencrypt/live/thoth.lab/fullchain.pem
        key: /etc/letsencrypt/live/thoth.lab/privkey.pem
    disable_remote_download: false
    upload_limit: 1024
    trusted_proxies: []
system:
    root_directory: /var/lib/pterodactyl
    log_directory: /var/log/pterodactyl
    data: /var/lib/pterodactyl
    archive_directory: /var/lib/pterodactyl/archives
    backup_directory: /var/lib/pterodactyl/backups
    tmp_directory: /tmp/pterodactyl
    username: pterodactyl
    timezone: UTC
    user:
        rootless:
            enabled: false
            container_uid: 0
            container_gid: 0
        uid: 988
        gid: 988
    disk_check_interval: 150
    activity_send_interval: 60
    activity_send_count: 100
    check_permissions_on_boot: true
    enable_log_rotate: true
    websocket_log_count: 150
    sftp:
        bind_address: 0.0.0.0
        bind_port: 2022
        read_only: false
    crash_detection:
        enabled: true
        detect_clean_exit_as_crash: true
        timeout: 60
    backups:
        write_limit: 0
        compression_level: best_speed
    transfers:
        download_limit: 0
    openat_mode: auto
docker:
    network:
        interface: 172.30.0.1
        dns:
            - 1.1.1.1
            - 1.0.0.1
        name: pterodactyl_nw
        ispn: false
        driver: bridge
        network_mode: pterodactyl_nw
        is_internal: false
        enable_icc: true
        network_mtu: 1500
        interfaces:
            v4:
                subnet: 172.30.0.0/16
                gateway: 172.30.0.1
            v6:
                subnet: fdba:17c8:6c94::/64
                gateway: fdba:17c8:6c94::1011
    domainname: ""
    registries: {}
    tmpfs_size: 100
    container_pid_limit: 512
    installer_limits:
        memory: 1024
        cpu: 100
    overhead:
        override: false
        default_multiplier: 1.05
        multipliers: {}
    use_performant_inspect: true
    userns_mode: ""
    log_config:
        type: local
        config:
            compress: "false"
            max-file: "1"
            max-size: 5m
            mode: non-blocking
throttles:
    enabled: true
    lines: 2000
    line_reset_interval: 100
remote: http://192.168.10.69
remote_query:
    timeout: 30
    boot_servers_per_page: 50
allowed_mounts: []
allowed_origins:
    - http://pterodactyl.lab
    - http://192.168.10.69
allow_cors_private_network: false
ignore_panel_config_updates: false
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZ0NqakdjczNwSGw1aDd4
            MTJHSTBONW9LTWxKMDlzT2owQkYwZWV0alY4ClJkZWEyWEJXUHVsY0lDRDZ6ZnA3
            U1JScURsa2xkQ0ZFMUNub09pNGlTM3MKLS0tICs1VEw5b0puRE9ZQ2Y0YUs1b29X
            SGtIQmNiYjNRQUV5cCtXaTNuTTNXYWMKBdUO/m/L+NbcCFJZNQzui2QEdgKdlFqv
            ON1SFljbTur74CpXkgFJQadHPxEHva0YWVBKzQ2OyKoS6PjuwpXsug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
    encrypted_regex: ^(token|token_id)$
    lastmodified: "2026-06-15T20:19:34Z"
    mac: ENC[AES256_GCM,data:FSCzrQ24dGETNVPbqIO0F0oYwoWXbuNhuNASnl5NibQzRmcqpgDNp+0tKbUWAlC8+JjUMJ/zz5ZM4+4E98P9qIfraW1oXCeOZamPSpxzMIgKA91+zM1QKbOuwGlKUuQzUNuvQJ3tSbYocVzyYliH4lb8Tt8sVwcFHN0+oNdD8GI=,iv:3g6UQ75vuOXQYRzp/4BimhatQ+YNn9qaShyIEG3FQPw=,tag:KCh9n00mLV7twrXLqqlGWw==,type:str]
    version: 3.13.0
