apiVersion: v1
kind: Service
metadata:
  name: suggestarr
  namespace: media
  annotations:
    metallb.io/loadBalancerIPs: 192.168.10.64
spec:
  type: LoadBalancer
  selector: { app: suggestarr }
  ports:
    - { name: http, port: 5000, targetPort: 5000 }
