apiVersion: v1
kind: Secret
metadata:
    name: bifrost-secrets
    namespace: bifrost
type: Opaque
stringData:
    UPSTREAM_API_KEY: ENC[AES256_GCM,data:1+t6gum14SqtS1dPEQB/M2FkhsQrEJgNJLyRvNKMdpresUM=,iv:lS4OU5GPsRA9WWpx5LEz6ovVOO6HVzDTb0t+xDO+wqU=,tag:sjpp8FDgn0Qhg1ZmI/t5Pg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbWY2VllOV01nVER2NURK
            Tkp6SnRKUVh5NDRYY2lHN2NaYjBzaHVmRUY0CnBtU2ZEZmVIcFFRNWV0c002S2pw
            d0cyV2w2bFRiSVJ5eGp4RE1PME5HSmcKLS0tIDhRcmpNWjFiZDByMTV2S1VsQ0RV
            NTY5Y0FkTGNHRkpQSzM0d0RIYzVUQ1UKw7j1/h+eEaE0VltnT6dcoDkByBA6qVv4
            F4NE7lkr3QASZScMhqLMy2R9S+NqwuKx19ssz67sx2YlJAhPrn2BAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUnNQeStnRXhJeWt4Qi9R
            QnBmTDZQRFVESk94Sk8wN3VmOGhxTHNyTEU4CjdicWRHOVR6UWtDekpqaHZkMHBx
            TXJCVEZqazlkNzMvOHZ6ZEpFZitVc1EKLS0tIGZwWEs1SXhud0ZFeTY3WUt6eHNr
            Ri8xSjhkeUxxc09EeWhqdGZsQ2N3em8KiS/denOY9EAng36mc7mkOBvsA7bS9jt9
            wAYKLYrivB0uPmjygutRAxatO1irAWvQbRoFU7Ro3TU/o7/OtTz72Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T16:37:46Z"
    mac: ENC[AES256_GCM,data:tkc/kNpeCOv6ETtdXhRNDpMrDkV6Y8cFx7JUKLtPfm1OjhrJX8NNnFvX4WbRZYlJwsTW6gi0sPrQQE8axrZYcmKCvvppHpCcpy3/REYHoFK2VZnkjHPo1J8MkjFetVGFGWXgNpDOdNf2dEGm7uB4xb/FIHLQgVawu2XksD26N8Q=,iv:1nmPXxm6B4h6P2BKSI2tjypeoWthDrZWxiop/zyRxb8=,tag:7rzqT93dw9Xn7pifW5Nn0Q==,type:str]
    version: 3.13.3
