apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent2-vpn
    namespace: media
type: Opaque
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:VG7WNfZ/E6s=,iv:QfmYUEmsbBFK5AIJR9SZ7ObLB7NwgZqv1Ls03uRRJ3s=,tag:mvtl8/1N7nIcLX/dpUdOvg==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:uZbZsCmXZNM37kPqkX0=,iv:NTxwSEiqB7rFzVHTS8M28U4xlEKpmc151c4AaofKvsI=,tag:oUZFfN3NpUbW/XXb+nWP0A==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:hqgwpK21zsw3QSeSK9A0u+nuUlwO3PanT5sqybv0LFXB6qpKZm4hqeQFYeI=,iv:PHkWFl8f5BlXRYVgsbzHMYgnDbAvPtfDC1/Mri+QaSQ=,tag:T4yJfj2kJhxQ8Kqy52GyGQ==,type:str]
    WEBUI_PASSWORD: ENC[AES256_GCM,data:mnLwoOamx0v5aQ0=,iv:HpMYdZSgGWUZZQ13O4oZGRu54lRD2VVipCVW/YO/Xlg=,tag:BCahZrLpIGkuvf6+ENcLQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSll6SmZUcUYvSW5WaEdl
            dC9Lb09laklNYmRTRmxFZzBTVlZHWWlqRGkwCk1JOU5wN2FSZ2FBcUdGOFBJWWIx
            dm9kL21sdWVhRUdtZW1JS1h5eGxUVmcKLS0tIHVRRlpsZitVTTFQZDg5cGJidkU4
            dFJBaDR5cDZIckxaNG9iU1lFcVRXRmsKMJHaRRGtpKmnXuGy/I+4+odM33WXGty1
            t8OBikX6pBi3u61KuVLT3nUoG84KarEdecT+neUacH/olK1nSsb5Dg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNK1pkdzFVWDZUK000NlVo
            dlVqc1dCQ2NtQ3Z6S3UyYWROR012T3VoOEI0CkR3RWtReUkxN0FNMDB4a2xSNC9E
            MHZZb3I3YzBGUE5oZmpmYjFhZDBuSGcKLS0tIDQvTm1wcTkzZlE3MThNb0haTGMw
            WS8vYkM3bmNmNGdZbWUrZldEeXpKSGMKY7uoxn2DxYd+4vQ+22kboq5Wu8J8qP91
            tOobV4JCxDaYLtKHAAdT7bWNSwIFve6DJERl5JYBcbLJk/2m5ph31w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T16:40:59Z"
    mac: ENC[AES256_GCM,data:yw3WeCxskSs2f7/C2sNpFga9qUjmFe7LCnGz+2r6Fra5dH8o6cdPimeR1PZGRDiQi6V7IZWrLG1KjfCTTCO3f1B9/OdvqPu1ZAL8tW0H5YMJUxyxUnwNUPDb7DeasnfPrFjFIdWI46167FRoWX27QDgcFFtCnShk8k1/rPgBSUc=,iv:B2kgIQldMdhCJKOJtaIS95a+Udx/u/nt1Ulpr+VTz3M=,tag:GShlkGnIucbRkdLLoEqyBQ==,type:str]
    version: 3.13.0
