apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent3-vpn
    namespace: media
type: Opaque
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:LALciQT+334=,iv:0NL63FoehsOTdv8t/811t8vddQ/M3pBQj7y91hJvVXg=,tag:RAJpwbcCCoe57g2iThw3Jw==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:0RB2DohWvvG76R4Xffg=,iv:gr9VZPisbjmX21BHLEvZtMkHDcZFwvJ1kJXSVHYi4Xo=,tag:aKrWplxGDB9ufQK83NN3xQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:X3xI1dS2PrEIUSGdIDtYe0ZS8vSPHOr9GmQBeJ+YfhXmmJ9A8PKi6xZKuMU=,iv:rW+CagGagYzR7AmbqwZvV2au+0TfjxW8Pn2OFomY+tg=,tag:PA/CgSAFXtNDbfkDtcgpwA==,type:str]
    WEBUI_PASSWORD: ENC[AES256_GCM,data:uo7Zq4PqyYwFo4k=,iv:OWDLWCOXWoOrHeRk/YNyv6RNEqq9X5/c2HjLIRt8ZIk=,tag:U6fCsVIPelDqNvOUkqZbPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL2hIdnd1OFlnNHlqSW1V
            SFpRQ09iU2lpR29kZHZ6eTdmSXkwVGRiZnlNCm5JSlBQS3MwQ3JkVUtPYXd0cFBj
            MGFsTmVCMXFtV1N2bDZORTljMTBrMVkKLS0tIHBPVGs5MUZNaG1GMFhXUXU3ek5M
            ajZ1SHU5c2pVOGI4dDEvZVJnQU1KNlkKoKAnzA7lc8dwlRM8vc50uwPp9Cr5QwoR
            +PUTHpNCTSGhINeycavg/Z+tG7kf+j9rTRLMQzXXw304sv6Nf7rO7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeXZsK09hc3JOT1VmUGVr
            aHFkK20xM0djTzdBTFFTSjRPNHRmWE5MR0dNCjF0NVJzblJwL0xoRDRZdTZtTTl1
            UEpPaGtIQk83VlpFZFVXNjFQbkpsT1EKLS0tIFpHQlF2eEIxK3U5L1BrZll5ajI2
            eDl3VzFqZVRYRHQ1RDIrZFhNbnVzb2sKTkAoa2OUAlg63kjuNrjC77QFje2L+24y
            kCkKVSX9M9VLO6qthFkcYd9EvmDEasuWvi9QtB5f4L4pkDCpEWR2vQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T06:23:32Z"
    mac: ENC[AES256_GCM,data:BJQVwcDHKXhM9OdG2BZjguYoASOb0oFBW9lt3ZBHkbmEDOrsTG3IZo1Rg0weYMgCdPQv3y7i1cmBICQIqJ+a2H+CPBDQgerSzSBxtDF45pQvPQcZNMdJcsod5qf+9Rf3nud7okwok/3g7g6/Pm+J5uLCi53YukXElq7ZQDFotzU=,iv:+4CtL3ckYAKF1EeI3gA78ypy00nP8iqvW1G/4/GQIZE=,tag:WJJCsuKXH5ZGb4nPNCKGrw==,type:str]
    version: 3.13.0
