apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-vpn
    namespace: media
type: Opaque
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:Ia7y6PXwEXY=,iv:yi5hrxG3oaMG7M11cBQVkTOAJ8dlO0UBEYjnOOWhNEU=,tag:8ylA+g+vgwlMaNPqQFXxGQ==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:iuqlSuCedRrHuaaOs3U=,iv:3j8lAJ+r2GhUgfLBwzlxY/5N09EnbXE8OhtXtUs4Lb8=,tag:8lIo+kw0Kg24OvF/pMy8rw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:GCRYC9W72n53eHtLDjpBGwVW7Azuopb40/O38I7pLKGr37VsJC7YRuULCRc=,iv:rhpf+g3Pv80iKVJlOPw5A5Y59k+ywIAL75ySaeD0dI0=,tag:fY0+2a3OeOj7ykNLsuyGaA==,type:str]
    WEBUI_PASSWORD: ENC[AES256_GCM,data:ejvmJReeePSm4TA=,iv:I4qfhKk10emiTyH6Diyj/sXRshhaVk1tLEPq7hhYxXs=,tag:noGI6t2+/du30l/NBVGqcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybVJzVG9oR2RkZWhxajMw
            UVFJZFJkNWFDZ0FZd0hCUXBEUG9NNWIrdVNzCkV2NjhSZHlEcWNkaEZCVy9oVUdn
            TUhCTENkQUNMcmQyb3c1UW1EbzlLdWcKLS0tIGVDNnVBQms1RDl4TUFSdzU1MGF1
            WlBEUWxuVnIxR2hGajdZSzFJcllIZ28KlUEP8eFvsS5/9IcPIVi65KoGuHHn0Jzs
            JYKwkebjJTGjViB9arH2+UtsoRvPW5fnu8M5SKMUdPWUKOQI/o4/zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMejFHanBHVXlCRUJyMUwx
            TjhSVHJjYjU1YWdSc0NZTncxV0twRjc4SVE0CkZuL1Bla1dnZ0lud0Z4YURjdTAr
            L01Rd0l2MmhCM0czN014NTF6cW42RDgKLS0tIHMwTWJ3K3piVFMwRWY5S21zTDNs
            Zy83ZjByQUU0UWVPQ2NpK0EvRUlFZG8KOsYJ+c30Kqw3fceJF6O7N9AzQ4f1v+Lr
            kMkd68GhwH4LnqkC3zxc85SqHjHJ+LNbhLBmV0SriJfCVcWr0VVuzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T00:35:53Z"
    mac: ENC[AES256_GCM,data:1bZEO19c/6bmqfXHlKmoev1/r+w1afbXtlbwbCFW/r+QFi1xT/W4KgESjW10d8w2V7JtAMODkCBGo5iHxcNQQPfqpocOtyhAp1TZ0YeGPCCxR6bNUmGYbxy/nARyuvvkV1aJ+Ax+JRqRlmlFe31sJ9S8+3ckPtCxCdJ8d8KpruY=,iv:SeI5IBRAScFMBwTfXu9Wm7fFq0uYu37qGTSTIysylwU=,tag:t82hGEWmXY2LfCIxzdXhGA==,type:str]
    version: 3.13.1
