apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
  annotations:
    metallb.io/loadBalancerIPs: 192.168.10.58
spec:
  type: LoadBalancer
  selector: { app: qbittorrent }
  ports:
    - { name: webui, port: 8085, targetPort: 8085 }
