apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
    namespace: media
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:xh11CBasZiv8HDRAedYRbG/TVKr4pE2HpoU6K7M9fo4=,iv:TqaxKfjxN5KBH6UJMlqtTxTerfgcPOu9SpJLvV/ghhc=,tag:I+JQg/C5UIkIKaczZDfL0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoR201ayswNzh0UHptL3dV
            NlFtTFBQcnMyOTkwOUFiZ0tjZERUTnUvdkVnCnRwSko5SFhIWFcyMlZ1bmQ4SEtI
            SlFnVTVqQVlURyt0MHphMEU2Z3pUcXcKLS0tIHJ0cUovUUpEdE51ZU1Bdmo3aEFi
            Mjc4eEtKMlJyMjBLQkFNQ3hSZVl6MmMK7V8iiRu5dk5gUkEQW0KktYnM0MSwi90y
            p5U1fgOL85ECq5yHCrxkHaW91JFpMyUw1lvD+aFUO3sTvmPGxD/0pA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYkM0ZmpvQlhieW54WEpi
            MlJTZDRjTWsveU5QVUNTSEJJYVRFN2hsMUc4CkZqWnF1cGJJVitpaCtHK3g5cDN0
            OGFSVkJuc1RoVmNPUndaVjhDdWpvRWcKLS0tIFBQZjdYemcybmtKQ29ab1k4aGJo
            Tmhvd2pSajZhRFh4NDJFQnI2RGhyVzgKHrBWdPzbOuQ9F1AyzPJLvtUJ/LHDaU0x
            gbPHkr9GxB8V+LaZgtRDiq1zJfBI1HhLQMRxiEudICxHQuBLfTBS8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T00:09:43Z"
    mac: ENC[AES256_GCM,data:e21vPgT+YmJbjPfW0SqWD6gZCL2VPegEToYKrvSHRT0D1kMBubOZXyobwEr4xJ8s3G8hZcAlRpoHCi+mxHqWtr0o/zrdJH0Z2OBcKw817bRNrkfs6y9oAOhT2+KZnMJcOSryGrf9DPvzfD4BcOAV6FFdDmdgQdb9VllfK9OuB1Q=,iv:vvwAYFPAXqKpiV37jHTENW+jdX/Q/yB7NUtOOKGdycc=,tag:ajpHuOotH8quE8Ewy4IlTQ==,type:str]
    version: 3.13.1
