apiVersion: v1
kind: Secret
metadata:
    name: subwave-secrets
    namespace: media
type: Opaque
stringData:
    deepseek-api-key: ENC[AES256_GCM,data:t4ZwXNetraFqU6j6JtRrsb7qpU4qoQcIISHqQmIUqwhTJn4=,iv:gaAwu0JYguNeOwMN40ynS85QwN1EQzVv/dA93d3xIZ8=,tag:E187bPh1yvcfQsijsIR4CQ==,type:str]
    elevenlabs-api-key: ENC[AES256_GCM,data:4Y0XINgUY7K8hdG77iiuA5poAqnvsOUQgLLMLJaZvOTJniBawQQN812A5HGY5EMoHkHO,iv:Y+7Yg+/yEhzVVsWut2vN6ajhuAvD9aOwSq+OYrllhUM=,tag:N5jX7FNWqI34Uy72CZ73HA==,type:str]
    google-ai-key: ENC[AES256_GCM,data:DkuQ1Z5Q/8gmdjPdH9rWGEVBKou+/uuVF9nxf1EEY8Ips5iBead39nUA9zA+3Y28kcZWMp0=,iv:ORkEbsUEQzW+LA0FN2RJthzaf+ISdsSKD6voeD518yo=,tag:izTVKetfuGozShzJ92NjaA==,type:str]
    admin-pass: ENC[AES256_GCM,data:ByZR/+1+MrNrdU4=,iv:zqRq8JHxC/x9QYLFsEgUq0rCxFQX6nxGrppdV6WIHKM=,tag:igq/Va2AORPI9M1bToJo/A==,type:str]
    navidrome-pass: ENC[AES256_GCM,data:t1n/LNi//c9DOFE=,iv:TlD/LxutVwiyaeYNm3uUJDETw0aY7Vb4bWu4ga/i/1c=,tag:542YYQd/MNqe1SScHcK3iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbDdUaVRDRFJES0FDeE4x
            bDQvWWpVZ0l0MGtIZmk3cm5iUDV6M21yWkFFCnJOVCtFWGt4RDFMdzdnNkNnazZ1
            UFNudVU0dkZCNDlWWFFmTjhMREN0a2sKLS0tIERBcFVGUUkyNENxYndJTFNMUEZo
            TTFGU3Q5dFV1ejZyQlVITEIyL2RsczAKXygM7Jygf2gF9WefKZ2G97wsjb8JWgTV
            s4Eb0WYMy0k3PQcdtJuoSGAIx9BaqgX4nybDLh+0N9DJ6ewQzGkduQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYTl0MGl6cDMvMjJJcDha
            dG9sZDZSQkt6RHhjV0xKd3hoek1uNFJEdlhRClBrK0JOWlpROHR4bFFpTmE3a25L
            bVF3YVhvT1NGRHZYOW1TbnJkd2RSSFkKLS0tIENRNUxHTTN5WllaTFNEQXpDQklm
            MUJQUjFnT0lRQUI5UVBKMkxxR2g4bVEKwjzCOWecQVmtnctGbBRzOiYt3iKAxf/K
            UBh0TH7x7szfLy8Rl+i8x+0Qt19u11ySuMnCCH4ot+IPoJzVv0D9jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-22T00:32:24Z"
    mac: ENC[AES256_GCM,data:pUlJykltEMOnNc8VuYlbJvdKhg+1g0/w1jiW/QC8mQebROec9xkm/P8CYIC9hNDKl2E9JJxK/L4FxxgtTvg4Jb2qQxrWg6OwMumYxwp5n1FctDnKIAI3TLZaGHrDSiPW+5kPyNV4WskTAtwNKGNUIsXEPkDivuy+yAjEzWUSedM=,iv:PybRW9Rgni+qfUjrTQSamqAjdEd9AwibYX2r4A1M25A=,tag:yj6tfaBnlDCwxY7QP8LX1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
