apiVersion: v1
kind: Secret
metadata:
    name: subwave-secrets
    namespace: media
type: Opaque
stringData:
    deepseek-api-key: ENC[AES256_GCM,data:BFuHAGKFR58vHKYmudRblmA1GiPOhDqf58dNbCaGKVY0zPw=,iv:ybDRHMryEpsf4ZKiAJMFucpd5u8ztGrGQlM5ZoU1Jsk=,tag:uuAcD8X66vdu1cjDToRTlQ==,type:str]
    elevenlabs-api-key: ENC[AES256_GCM,data:26udx9xVmlNWXYUEnr86G+i6UlZFd6A4w60OJXanGHny7AfwOONwHxupysFLeNeB8hxC,iv:DrsB6+P9dJwgalHhq9jak20G+lIQ42uDkQ6t3aFfEK4=,tag:a5EYrZp5pQ1d6G8TpewEAQ==,type:str]
    admin-pass: ENC[AES256_GCM,data:8mMf8KT0rAPeMog=,iv:i6ySeEs/QBW4T/kvyBct0dE5vbVp0rRgKqBhalf5oC8=,tag:xlGJMfDdzggl7fAtfpMN5g==,type:str]
    navidrome-pass: ENC[AES256_GCM,data:45aiwmHk81XZ6Jk=,iv:bKl4tyYIDYmHIB7Wbw/+6bPKjhy8uaOncviIMxONX8g=,tag:zf4DA6wu5+/Rv2+YidEBuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNnJhb2FxeFB5ZVRKQXdB
            RzhBSUNSc081MUx5UlVJZTZ2L3NaU29NSGdjCnpCNS92bVFuMzE3UHg1b2pvWHA3
            QndpRnprM1l5b1pweVVScmhNbFMzdGsKLS0tIDcrTURJa3RhR1NNSFNKRlpsRURE
            eG1FQ0RtUHhObytrYVdmK2xBbGl5UkkKOXL7S2j57hR34Tf+47fXEIH/z9NiU09R
            P02MY6ie8XTElp6Ew3Pc3dteQK8L5nhrbivXtjeiXSqx8igNNB0tkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvV1JnYUV5K0JNN2cyK1lU
            MnhXZDFzY0lBL2RlYlJmTk9iRTBmTlFhTGxNCjUweG5uK3dkSHRRUHNGK1VCZHVN
            UW00Z051U1F5dWlZNGx1bThEajRVUUEKLS0tIFRUR0pmM0dVOTMycjhlcFd4Z0lV
            ZjROTFVpV0t4dVdML3VJN1NDQTFaNlkKE8fngd4GCjOnNOD0abS1xENdC0qDqZBb
            ha2GOanpAmWgN5LXsQYQrN5PnZ68dk1ISQaoKIcYjqvf7fUw9p6ctA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T17:44:03Z"
    mac: ENC[AES256_GCM,data:Xssz9Fkbnpn2FmyipxhPgPghhYXGDvuVoADReqWhqNbvmaj3HuO3PdB6F4MZxxFhiUTAlevTikQDDWwCkF0cUaMzN8qow38SbRfuq+8sk59RA3uY0drgkUTd/6e7mWNUOiuAz7cym/f5TtFmqwwdvAPity+focZR/9tOkyEcWXg=,iv:8J/bnVWFPFEKQMtAk+H9xLMSwRmf0j2aNZEcQR96zgY=,tag:1Rjdwk3KOW/95vGWePVaDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
