apiVersion: v1
kind: Service
metadata:
  name: subwave
  namespace: media
  annotations:
    metallb.io/loadBalancerIPs: 192.168.10.91
spec:
  type: LoadBalancer
  selector:
    app: subwave
  ports:
    - name: web
      port: 7700
      targetPort: 7700
    - name: controller
      port: 7701
      targetPort: 7701
    - name: icecast
      port: 7702
      targetPort: 7702
