apiVersion: v1
kind: Secret
metadata:
    name: jellystat-secret
    namespace: jellystat
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:iSEhbtXMDnj3nG0=,iv:yJtYqZGQjT4R6tavPyVpAMd1WILz17MByL9DeR9H5CQ=,tag:Nm3u0IRCovoYivo/eJwqzg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:u4+bNH5oje5wYS4XdgdO3dH6dJIsFcI03rFV77NTCR4MoQWoBYb64Eh7ovxWxcIm6o16yxB2ekUC0JBrebsAoA==,iv:UEp0fjMLAdtaoTx872DQ4jX8s8A2Wp7ZaI8eroHXOBY=,tag:FJrtPJX/FJlRpOq8FUO3ug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUTRWcmtsNXpBYzgrZFBw
            YkhTenNBK0FQT0RXSHljSGROQlNkS0RSc2hjCnhpQW54ZU9YdFl0WTJhMHl5eUVh
            Q3pxUitwaXZOOWtwcmlQdnZNYmdzeU0KLS0tIHZJWUdmd3o5U3l2QVd5MUNHN0pz
            OWh5N2IrMlB6bHVyYkUyVjVoRjMzUWsKQ0xJcGiIzC1he8THSm3URFWmPLukdvcr
            3iFBF2JgfY51RR4bW1Gh2c8EOOz7vAlPpOY7JG8UVUj+Sq1M61faZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNFN6RnpKejVPNllJYllV
            YkM5aFBHMm9OUnNxZnVnVkY4SDNnUi9YQ2pFClQwVkJocm1PdXFhSng1ZW1qMFpJ
            NXRJZzBDZlBQSE53L3dGam5LMEF1SjAKLS0tIEk0bW1KVFVUak5NQmhDTW8wUkRz
            MVEwK2lpL0oyaDZQekVtazNuYlJJN28K/UpA1rytG8bQF6SRwemksjvSkYhx8v1w
            MuPixTt9bVPSXVx7SYjuAvRIFjPQVQJsvlCbn56Zut1Lo9r0oIPycw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T00:35:13Z"
    mac: ENC[AES256_GCM,data:fOVOIMxSslqwhnnn1nJGpWoAniKnBiekBy8sW4bFc+EpwJEJTqjLAlGjRMkUpcdAG1MdhNlxGZPWeT3eLTEZC7S64O08U49T+unBcpkrATgBRirAPwMskPIoo0ballgDGJv/nL1Fo6tc/9yX28BsodpreHIOWazkDsfTY6yFROA=,iv:Q1VJMl0RdUUllbsEQKt0IMcx5GVPIQwxj5aeaw1b64c=,tag:XUyA+MX3GnTJ8AKQwlN14Q==,type:str]
    version: 3.13.0
