apiVersion: v1
kind: Secret
metadata:
    name: caldera-secrets
    namespace: caldera
type: Opaque
stringData:
    CALDERA_API_KEYS: ENC[AES256_GCM,data:wVUWplCx16uXi1VAa8HzSh9HnHo9bId7qgb6GFluFysDR+8TeDqIJaxEJX++35GbImyUXsi3Gzb8htWuoW3N1g==,iv:Ez+TvabrAUaYFtQE11+eT3fMVVRLBmIh5gvLIPGx8YU=,tag:oGetKGCzZs1JgbbKQXtcZw==,type:str]
    CALDERA_GITHUB_TOKEN: ENC[AES256_GCM,data:Tr6VAVgDM0PSXWXvbnGOYT3oRW/R,iv:GzgU2Vz6fXvBjq4MFIVB2mKdNh80MMU6xxhy/dHlcLU=,tag:lzHU20WUHObtrvNBl8tIFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvT1NnQWJQWUVVNkcrS1pZ
            aE1XMVVIOVFxUXB0d2NDU2xqV25yWS9NNkE4CjZJcVBjVTJGWmxQTHU3OHFENGlZ
            UTNKM2JXTXMrR3pHL0p1SWl0VU1pK00KLS0tIEpSeHZScWVGemxFclFJeXJwSzFP
            T3VJODVXOElKdXlxSEd0NnVWNFdUMVUKk8dWysGZK9FocGYxZoBIft2JrrwJUfzd
            RADe1qdNt4ddHQ5bGZz6+fHRAHUI0OtsBovJgr9T2MzbcIoUqGx+Nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN0dtOTlIQ3F6ZGsxc1BG
            Y001V2pxc1dTTzlnRHd0bVdTUXVYRmsxY1ZBCkdMNFMweVJQTWd4elR4Qm5JanlB
            WUVTazFOT3EzVHhrdVpHbWc0c1hReEEKLS0tIElVZ2k3RGh5d1h0eFA2dEFWM21Q
            M0ZtMzNpYkJtbHo5NGpld2ZEcWhEZ0UK0Kp/FT+EwkvAgFCTd4jWiLIVjhTLGH5N
            Fb5fXSUKQbLnrzZgN2udMbFNX8VPKr4a2jqSmi9m8p/jNvFBbuRsPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T02:02:59Z"
    mac: ENC[AES256_GCM,data:YYQKaeUtRvoBhOYbTq1x1kfGBhyxxZbb8eoqGIOH/uY5WpXk6Yd7Ul4fSuv0SFtXD/2LBo4Iiyz3TzjgQ9ONXUTs/VzK+KsAsmlMT/yrMvJDIysYgzhNbHTKJEdGh/nP9OD1tumpP1DU8KI7yEG+jtJsPX0JPKDSJAXj5kt3fKw=,iv:17SZPSEfXXz8AYX3dJOd3BPAmOT3fPKr0KtebE4nknc=,tag:n8fnDTgeQywXQ1U13K4sww==,type:str]
    version: 3.13.0
