apiVersion: v1
kind: Secret
metadata:
    name: caldera-secrets
    namespace: caldera
type: Opaque
stringData:
    CALDERA_API_KEYS: ENC[AES256_GCM,data:wVUWplCx16uXi1VAa8HzSh9HnHo9bId7qgb6GFluFysDR+8TeDqIJaxEJX++35GbImyUXsi3Gzb8htWuoW3N1g==,iv:Ez+TvabrAUaYFtQE11+eT3fMVVRLBmIh5gvLIPGx8YU=,tag:oGetKGCzZs1JgbbKQXtcZw==,type:str]
    CALDERA_GITHUB_TOKEN: ENC[AES256_GCM,data:wN/mFnya1lL3VcH+o2yUyQT++6xKCb4g30hZ3cUltIzPUnuI1qAFGgBK3xjmAUMcnS43tJwDqJeVtmfFr/11phzA7kyziDGcS7OaLnS7eNvFEbswHa7/GTbA1RQw,iv:OqEFjwkCtxKsoLfRgWo9LsIA8/tfXpupP6YKlAIfEPY=,tag:UTbkghNGSCKTv5mreRCUhA==,type:str]
    CALDERA_WEBHOOK_SECRET: ENC[AES256_GCM,data:ItAhI8x+f9ttKH0LczpqRNrI2YWbqLngvSpz/o2lgf6xxx94m2Ka6xw4GyDWp9AQ6egZgFBvC6HIrfxjOBycHA==,iv:yNeAiob5hSyvYs34KAl+fU9xpLfHx2cxgTAQCNaEIuE=,tag:xXFtLBBANa8ZGUZTtNycJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvT1NnQWJQWUVVNkcrS1pZ
            aE1XMVVIOVFxUXB0d2NDU2xqV25yWS9NNkE4CjZJcVBjVTJGWmxQTHU3OHFENGlZ
            UTNKM2JXTXMrR3pHL0p1SWl0VU1pK00KLS0tIEpSeHZScWVGemxFclFJeXJwSzFP
            T3VJODVXOElKdXlxSEd0NnVWNFdUMVUKk8dWysGZK9FocGYxZoBIft2JrrwJUfzd
            RADe1qdNt4ddHQ5bGZz6+fHRAHUI0OtsBovJgr9T2MzbcIoUqGx+Nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN0dtOTlIQ3F6ZGsxc1BG
            Y001V2pxc1dTTzlnRHd0bVdTUXVYRmsxY1ZBCkdMNFMweVJQTWd4elR4Qm5JanlB
            WUVTazFOT3EzVHhrdVpHbWc0c1hReEEKLS0tIElVZ2k3RGh5d1h0eFA2dEFWM21Q
            M0ZtMzNpYkJtbHo5NGpld2ZEcWhEZ0UK0Kp/FT+EwkvAgFCTd4jWiLIVjhTLGH5N
            Fb5fXSUKQbLnrzZgN2udMbFNX8VPKr4a2jqSmi9m8p/jNvFBbuRsPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T03:00:41Z"
    mac: ENC[AES256_GCM,data:UP2mV4QHRCkLP1cch8PAIdX3MhXTbRUjST0O0x1PAwRooXlTFhkKgmYtDmWBR5H2r0RTR50YMt1KYz02n0fdPGyzglIyoD1aQRDkO/xJfiNuiCBF0L2eOt5gvnz8WyWTHqPaaRF8boCxlQoOpIdudt5kW3FCWb3PeX2pge2TBe4=,iv:Rr0dL6i+MmBvyhdfjAwgzgzGtyHi4bqVmLz7t/DfZyQ=,tag:L8fZLX6zXpJiW8FV3QdQMA==,type:str]
    version: 3.13.0
