apiVersion: v1
kind: Secret
metadata:
    name: ignis-secrets
    namespace: ignis
type: Opaque
stringData:
    IGNIS_GITHUB_TOKEN: ENC[AES256_GCM,data:pYrRvSi3aJwnd5pTDViLBNEYSoosDFOtYMVNZurNO8ki1SE5JYxCh+Yeh2LOGWVh3PbvsU9jR+wR3JV4MxfQd0FKPhPuIJM8W8TQ8yLM/LZczdvdL9eJf8TfSfHB,iv:4/dZiaY3r/yCKg8yYQWbnYcgmuHbjAMA7v+cuAPuK3Q=,tag:oo6/XRtrpIFjgrQV3LpbOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzc2hpY1IvNG9PSi80SXRw
            ZzFaQWZGdk5UK212SVZJSHUyVVdxUW9OcjBRCnVkVGh2eWpVUjRqSVp0T3FRb2Nz
            QVRUK2VsejM2NCs1bWxRZU9vRGNMc2MKLS0tIFZMTGZraEdSTDBERCt2T1A0OFdl
            VkFyNUdmWngzVWdUNXJBb1VnYkl6SU0KYBhkm+fkM1/2j6MybRUfdMfC0blYl0Wl
            j5rxwM8ix8sJb9i2ZqHmxkrJ3J0LbCMG+m7h5s5q/Y6k8wWak54NLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QUpaVURSSzRsQ0Q5MWVz
            by94NkNrdG04UEl4blh3VjhkeTBRZHoyNVZ3Cmt6RnBCOElOL0EwMnlGVnBZbmZ6
            RlFUdWpFZXNCenJVbVA3Sk1FTTNXVmsKLS0tIFBSUWtYQVpvckdaTncrU293QjY2
            TkZaMEhUR0pmbW52c2t1K2tKZGw0RncKROUY87lMDTCZhSxrE0EzClRJfJYckzKP
            DDxZyI69cm7DS5s/XBiIAoHpyIdSjhR9eq4CUtcEabdJ3X+MMmoUcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T05:06:29Z"
    mac: ENC[AES256_GCM,data:PYKC4Jya5zWEhQ7jb4wT8H4G1wR4dDA2yTnuasGhYkCdnY+J02RtTuIO59kpkr4SC1nW/oQ/Alzb9B/OZxTobWN1+jb/SrH1VzPcbVYTK1VNeOaUczRkUP8lEkNxy1JPCris36f0tYTpkN0MOPwKeH/+kQhbNaVdeFPp7u0bOOE=,iv:Ah47lWRqu4UsScWIBTe4ZAAdXr5T3/d/omgU/P4EPoo=,tag:d04UOcaegZsxqrsBZTogdw==,type:str]
    version: 3.13.3
