apiVersion: v1
kind: Secret
metadata:
    name: subwave-discord-bot
    namespace: subwave-discord-bot
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:0W+AN9LgBT9W2/uHbkmtx+OUG+uuBeNHFSfqcXRJYiGNBBFCSxncznVKdp4B4yloFkJvhLozH1hlHNDxJmbT8mmofTfhv8k9,iv:Qzipb3VIMTGZZJ/tESTx/f3CWDJovw5Pga0GjfJ/Ahg=,tag:nmLWtZgOv0zvzf5kkhZGpw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUEYrb0cxc1dhTmNHci9E
            aGQ0N08xSVhhR2x5aDE3dndLdWREZG1xeEQ4CkkzR3p6eVRGbm9ia05rY3MrdTFD
            aVphV2JERW1LWU1DZkFNWHk1QW0yMjQKLS0tICs3MkdMakpWVk1BelROQTczOUZZ
            cDVsVUdITjJ4cXVvVUVWREtiYU9FVzAKsc1aePFHqpSaL1X4VaOknhQnPFPNXWsu
            FhJpEQ3oz4AUJv92Pvw+n1n5rhCz2LtPGG9oP71R9aNrjufjju13+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8tfm7scg35csrnam9ntnppne5728593yw7fk3p9sz7ecl06dpgs958ncm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVmhQZ05VVG1ielI2UFd2
            RXp3RWtBYXlNaFAySWlyaVppOFlGSHBaSlJZCit1eFRTUDZsKzM0Qjc1NnZ1QUs3
            bGdDbjMzbHFuQ2xMOVUvVlVuNGFuVUEKLS0tIFZydytXQlVQYW9OQldOYzBraGEy
            ejNkb0VHQ241SWNaZjBRWkloTTd4MjAKtELvLMTms3/Gj4uMCz7zSrO9OdYMZuG4
            Z5w6CM3ECtqOU/RWIJor/I6cKCLYRfQJOIlcs+7nmxM/7pMRZDNffQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjvfq7kt5z04q3r04k9l2exjxuql0y8n0tq7qxylrjs5vn8ss5pqkv9x59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T17:45:50Z"
    mac: ENC[AES256_GCM,data:fXI8/LB8PKhfKUzMoE7onq7dbA/lx8coHsEtgOtLaJNZToolrvcpESgIPoF/5eoWO3l3tOuFjYUGk0pntn59PvY0/23u4TqOTVyKv2Y4p/Vth45CgeS2HG1SD5KGLA0rruWIpzR0cY6bUwT3RvehavExUTbpVQTaO3g3COrVk54=,iv:jPJqefEto4cjf9hpbA42v4iGUTAxEtD2eQW6psrk1FY=,tag:/CuW9s8oHr14L9FK+sBEdA==,type:str]
    version: 3.13.3
